[package]
authors = ["cbreeden <github@u.breeden.cc>"]
name = "font_shape"
version = "0.1.0"

[dependencies]
table_derive = { path = "table_derive/" }
byteorder = "*"
derive_more = "*"
bitflags = "*"
min_max_macros = "0.1.1"
try_opt = "*"
